---
# pihole-update.yml

- hosts: all

  tasks:
    - name: pihole update
      shell: pihole -up
      register: out
      # failed_when: "'Everything is up to date' in out.stderr_lines"
      #failed_when:out.stdout.find('Everything is up to date') != -1
      when: 'Everything qis up to date' in out.stdout
    - debug: var=out.stdout

