---
# pihole-update.yml

- hosts: all

  tasks:
    - name: pihole update
      shell: pihole -up
      become: true

    - name: waiting for server booting up
      wait_for:
         path: /tmp/foo
         search_regex: "[✓] Everything is up to date!"
         state: started
become: false
