---
# pihole-update.yml

- hosts: all

  tasks:
    - name: pihole update
      shell: pihole -up
      register: out
      failed_when:  "Everything is up to date" in out.stdout_lines
    - debug: var=out.stdout_lines

