---
# pihole-update.yml

- hosts: all

  tasks:
    - name: pihole update
      shell: pihole -up
      register: out
      failed_when:  "'hi' in out.stdout_lines"
    - debug: var=out.stdout_lines

